@startuml
title Week 8 – Command Pattern Sequence (single button press)

/' Actor and invoker '/
actor Cashier
participant "PosRemote\n(Invoker)" as PosRemote

/' Concrete commands '/
participant "AddItemCommand\n(Command)" as AddItemCmd

/' Receiver and domain collaborators '/
participant "OrderService\n(Receiver)" as Service
participant "ProductFactory" as Factory
participant "Order" as OrderDom

== Add item flow ==

Cashier -> PosRemote: press(slot 0)
PosRemote -> AddItemCmd: execute()

AddItemCmd -> Service: addItem(recipe, qty)
Service -> Factory: create(recipe)
Factory --> Service: Product
Service -> OrderDom: addItem(LineItem)

== Undo Item flow ==

Cashier -> PosRemote: undo()
PosRemote -> Service : execute()
Service -> PosRemote


@enduml
